[workspace]
members = ["client/app", "client/config","lib", "providers/direct", "providers/vk", "transports/socks"]
resolver = "2"

[workspace.package]
version = "2.0.0"
edition = "2024"
repository = "https://github.com/Urtyom-Alyanov/turn-proxy"
authors = ["Urtyom Alyanov"]

[workspace.dependencies]

[profile.dist]
inherits = "release"
lto = "thin"
